name: Update Registry

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip update')"
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      - name: execute py script
        run: |
          python -m pip install --upgrade pip
          pip install --user -e git+https://github.com/wsp-sag/network_wrangler.git@develop#egg=network_wrangler
          python update_registry.py

      - name: commit files
        run: |
          git config --local user.email "david.ory@gmail.com"
          git config --local user.name "DavidOry"
          git add -A
          git commit --allow-empty -m "GitHub Action automated registry update" -a

      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: staging
